//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SuperSales
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sale item.
    /// </summary>
    // *** Start programmer edit section *** (SaleItem CustomAttributes)

    // *** End programmer edit section *** (SaleItem CustomAttributes)
    [AutoAltered()]
    [Caption("Товарная позиция")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SaleItemE", new string[] {
            "Amount as \'Количество\'",
            "Product as \'Товар\'",
            "Product.Name as \'Товар\'"}, Hidden=new string[] {
            "Product.Name"})]
    [MasterViewDefineAttribute("SaleItemE", "Product", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class SaleItem : ICSSoft.STORMNET.DataObject
    {
        
        private int fAmount;
        
        private IIS.SuperSales.Product fProduct;
        
        private IIS.SuperSales.Sale fSale;
        
        // *** Start programmer edit section *** (SaleItem CustomMembers)

        // *** End programmer edit section *** (SaleItem CustomMembers)

        
        /// <summary>
        /// Amount.
        /// </summary>
        // *** Start programmer edit section *** (SaleItem.Amount CustomAttributes)

        // *** End programmer edit section *** (SaleItem.Amount CustomAttributes)
        public virtual int Amount
        {
            get
            {
                // *** Start programmer edit section *** (SaleItem.Amount Get start)

                // *** End programmer edit section *** (SaleItem.Amount Get start)
                int result = this.fAmount;
                // *** Start programmer edit section *** (SaleItem.Amount Get end)

                // *** End programmer edit section *** (SaleItem.Amount Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SaleItem.Amount Set start)

                // *** End programmer edit section *** (SaleItem.Amount Set start)
                this.fAmount = value;
                // *** Start programmer edit section *** (SaleItem.Amount Set end)

                // *** End programmer edit section *** (SaleItem.Amount Set end)
            }
        }
        
        /// <summary>
        /// Sale item.
        /// </summary>
        // *** Start programmer edit section *** (SaleItem.Product CustomAttributes)

        // *** End programmer edit section *** (SaleItem.Product CustomAttributes)
        [PropertyStorage(new string[] {
                "Product"})]
        [NotNull()]
        public virtual IIS.SuperSales.Product Product
        {
            get
            {
                // *** Start programmer edit section *** (SaleItem.Product Get start)

                // *** End programmer edit section *** (SaleItem.Product Get start)
                IIS.SuperSales.Product result = this.fProduct;
                // *** Start programmer edit section *** (SaleItem.Product Get end)

                // *** End programmer edit section *** (SaleItem.Product Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SaleItem.Product Set start)

                // *** End programmer edit section *** (SaleItem.Product Set start)
                this.fProduct = value;
                // *** Start programmer edit section *** (SaleItem.Product Set end)

                // *** End programmer edit section *** (SaleItem.Product Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SuperSales.Sale.
        /// </summary>
        // *** Start programmer edit section *** (SaleItem.Sale CustomAttributes)

        // *** End programmer edit section *** (SaleItem.Sale CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Sale"})]
        public virtual IIS.SuperSales.Sale Sale
        {
            get
            {
                // *** Start programmer edit section *** (SaleItem.Sale Get start)

                // *** End programmer edit section *** (SaleItem.Sale Get start)
                IIS.SuperSales.Sale result = this.fSale;
                // *** Start programmer edit section *** (SaleItem.Sale Get end)

                // *** End programmer edit section *** (SaleItem.Sale Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SaleItem.Sale Set start)

                // *** End programmer edit section *** (SaleItem.Sale Set start)
                this.fSale = value;
                // *** Start programmer edit section *** (SaleItem.Sale Set end)

                // *** End programmer edit section *** (SaleItem.Sale Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SaleItemE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SaleItemE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SaleItemE", typeof(IIS.SuperSales.SaleItem));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of SaleItem.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSaleItem CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSaleItem CustomAttributes)
    public class DetailArrayOfSaleItem : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SuperSales.DetailArrayOfSaleItem members)

        // *** End programmer edit section *** (IIS.SuperSales.DetailArrayOfSaleItem members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SaleItem by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SaleItem.
        /// </summary>
        public DetailArrayOfSaleItem(IIS.SuperSales.Sale fSale) : 
                base(typeof(SaleItem), ((ICSSoft.STORMNET.DataObject)(fSale)))
        {
        }
        
        public IIS.SuperSales.SaleItem this[int index]
        {
            get
            {
                return ((IIS.SuperSales.SaleItem)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SuperSales.SaleItem dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
