//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SuperSales
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sale.
    /// </summary>
    // *** Start programmer edit section *** (Sale CustomAttributes)

    // *** End programmer edit section *** (Sale CustomAttributes)
    [AutoAltered()]
    [Caption("Продажи")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SaleE", new string[] {
            "SaleDate as \'Дата продажи\'",
            "Client as \'Клиент\'",
            "Client.Name as \'Клиент\'"}, Hidden=new string[] {
            "Client.Name"})]
    [AssociatedDetailViewAttribute("SaleE", "SaleItem", "SaleItemE", true, "", "Товарная позиция", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("SaleE", "Client", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SaleL", new string[] {
            "SaleDate as \'Дата продажи\'",
            "Client.Name as \'Клиент\'"})]
    public class Sale : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fSaleDate;
        
        private IIS.SuperSales.Client fClient;
        
        private IIS.SuperSales.DetailArrayOfSaleItem fSaleItem;
        
        // *** Start programmer edit section *** (Sale CustomMembers)

        // *** End programmer edit section *** (Sale CustomMembers)

        
        /// <summary>
        /// SaleDate.
        /// </summary>
        // *** Start programmer edit section *** (Sale.SaleDate CustomAttributes)

        // *** End programmer edit section *** (Sale.SaleDate CustomAttributes)
        public virtual System.DateTime SaleDate
        {
            get
            {
                // *** Start programmer edit section *** (Sale.SaleDate Get start)

                // *** End programmer edit section *** (Sale.SaleDate Get start)
                System.DateTime result = this.fSaleDate;
                // *** Start programmer edit section *** (Sale.SaleDate Get end)

                // *** End programmer edit section *** (Sale.SaleDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sale.SaleDate Set start)

                // *** End programmer edit section *** (Sale.SaleDate Set start)
                this.fSaleDate = value;
                // *** Start programmer edit section *** (Sale.SaleDate Set end)

                // *** End programmer edit section *** (Sale.SaleDate Set end)
            }
        }
        
        /// <summary>
        /// Sale.
        /// </summary>
        // *** Start programmer edit section *** (Sale.Client CustomAttributes)

        // *** End programmer edit section *** (Sale.Client CustomAttributes)
        [PropertyStorage(new string[] {
                "Client"})]
        [NotNull()]
        public virtual IIS.SuperSales.Client Client
        {
            get
            {
                // *** Start programmer edit section *** (Sale.Client Get start)

                // *** End programmer edit section *** (Sale.Client Get start)
                IIS.SuperSales.Client result = this.fClient;
                // *** Start programmer edit section *** (Sale.Client Get end)

                // *** End programmer edit section *** (Sale.Client Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sale.Client Set start)

                // *** End programmer edit section *** (Sale.Client Set start)
                this.fClient = value;
                // *** Start programmer edit section *** (Sale.Client Set end)

                // *** End programmer edit section *** (Sale.Client Set end)
            }
        }
        
        /// <summary>
        /// Sale.
        /// </summary>
        // *** Start programmer edit section *** (Sale.SaleItem CustomAttributes)

        // *** End programmer edit section *** (Sale.SaleItem CustomAttributes)
        public virtual IIS.SuperSales.DetailArrayOfSaleItem SaleItem
        {
            get
            {
                // *** Start programmer edit section *** (Sale.SaleItem Get start)

                // *** End programmer edit section *** (Sale.SaleItem Get start)
                if ((this.fSaleItem == null))
                {
                    this.fSaleItem = new IIS.SuperSales.DetailArrayOfSaleItem(this);
                }
                IIS.SuperSales.DetailArrayOfSaleItem result = this.fSaleItem;
                // *** Start programmer edit section *** (Sale.SaleItem Get end)

                // *** End programmer edit section *** (Sale.SaleItem Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sale.SaleItem Set start)

                // *** End programmer edit section *** (Sale.SaleItem Set start)
                this.fSaleItem = value;
                // *** Start programmer edit section *** (Sale.SaleItem Set end)

                // *** End programmer edit section *** (Sale.SaleItem Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SaleE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SaleE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SaleE", typeof(IIS.SuperSales.Sale));
                }
            }
            
            /// <summary>
            /// "SaleL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SaleL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SaleL", typeof(IIS.SuperSales.Sale));
                }
            }
        }
    }
}
